name: Tests
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test of Compiler
    steps:
    - name: Clone GIT repo
      uses: actions/checkout@v4
    - uses: korandoru/setup-zig@v2
      with:
        zig-version: 0.14.1

    - name: All Test
      run: zig build test
