name: Tests
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test of Compiler
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.1

      - name: All Test
        run: zig build test
